HW#6: Tests for app.
ksko-git/localization-helper-application-on-swift pull request #7
Opened 2020-11-20 12:41 UTC by ksko-git

2020-11-21 16:10 UTC, chrnsv requested changes

2020-11-21 16:10 UTC, chrnsv commented on Sources/localisation-helper/Delete.swift
> +public class Delete: DeleteProtocol {
А зачем public?

2020-11-21 16:10 UTC, chrnsv commented on Sources/localisation-helper/Delete.swift
> +            return .SomethingGoWrong
кодстайл

2020-11-21 16:10 UTC, chrnsv commented on Sources/localisation-helper/ValidationResult.swift
> +public enum ValidationResult {
Обычно, стараемся получить максимум информации о том, какая ошибка произошла, чтобы потом понять что чинить, тут получилось наоборот, куча разных успехов (при том, что мы, обычно, знаем что запустили (search/update/delete...)), но только одна общая ошибка. Забавно, кстати, будет, если `search` вернет `SuccessfullDelete`:) А Result решила не использовать или не разобралась как использовать?

2020-11-21 16:10 UTC, chrnsv commented on Sources/localisation-helper/localisation-helper.swift
> +        Search(dictionary: Dictionary(), terminalOutput: TerminalOutput())
лучше `Dictionary()` и `TerminalOutput()` вынести в переменные, если нигде отдельно не используются, то можно в приватные

2020-11-21 16:10 UTC, chrnsv commented on Sources/localisation-helper/localisation-helper.swift
> +        return 1
Получается, что любой успех – 0, а любая неудача – 1, это возможное поведение, но что если тест, который завершился неудачей, но не потому что ты передала неверные параметры, а потому что он не смог считать словарь

2020-11-21 16:10 UTC, chrnsv commented on Tests.sh
> +allTests[5]="delete -k dia -l pt"
Можно добавить как минимум 2 успешных теста на `delete`, нужны тесты на `help` и неудачные варианты тестов (неправильные аргументы)

2020-11-21 16:10 UTC, chrnsv commented on Tests/localisation-helperTests/MockTerminalOutput.swift
> +    var consoleOutputResult: ()
`result` для функций, которые ничего не возвращают, можно не писать:)

2020-11-21 16:10 UTC, chrnsv commented on Tests/localisation-helperTests/TestArgumentParser.swift
> +                XCTFail()
Давай добавлять сообщение об ошибке в таких случаях

2020-11-21 16:10 UTC, chrnsv commented on Tests/localisation-helperTests/TestArgumentParser.swift
> +
Также нет части тестов на удаление и нет тестов, которые должны приводить к ошибке парсинга

2020-11-21 16:10 UTC, chrnsv commented on Tests/localisation-helperTests/TestDeleteOption.swift
> +        super.tearDown()
а `delete`?)

2020-11-21 16:10 UTC, chrnsv commented on Tests/localisation-helperTests/TestDeleteOption.swift
> +        XCTAssertEqual(result, ValidationResult.SuccessfullSearch)
Проверка работы со словарем и `output` (если нужно)?

2020-11-21 16:10 UTC, chrnsv commented on Tests/localisation-helperTests/TestSearchOption.swift
> +        XCTAssertEqual(result, ValidationResult.SuccessfullSearch)
Тоже проверки на работу с зависимостями

2020-11-21 18:07 UTC, ksko-git commented on Sources/localisation-helper/Delete.swift
> +public class Delete: DeleteProtocol {
Нужно было сделать "библиотеку" полностью публичной
Я так поняла

2020-11-24 12:05 UTC, chrnsv commented on Sources/localisation-helper/Delete.swift
> +public class Delete: DeleteProtocol {
Наоборот, публичным в библиотеке должно быть только то, чем мы пользуемся извне. На данный момент мы пользуется только функцией `localisationHelper()`, так что делать публичным все остальное излишне.

2020-11-24 12:40 UTC, chrnsv requested changes
Получилось не очень аккуратно с обработкой ошибок, которые выбрасываются через исключения, я уже писал кому-то в ревью, но если проследить путь ошибки от начала и до конца, получится, что мы, выбросив ошибку при получении данных добросили до места, где запускаем программу и там тоже не стали ее обрабатывать, так она и ушла непонятно куда. Лучше всего обрабатывать ошибки на том уровне, на котором мы вызвали функцию, которая ее может выкинуть и уже там решать что с этим делать, продолжать работать не обращая внимания или выбросить другую ошибку, которая больше подходит по смыслу для этого уровня абстракции. Например, если нам не удалось записать в файл, то репозиторий должен выдать максимально подробную информацию об этом, на уровне где мы поймаем ошибку, нам уже не так важна дополнительная информация, мы завершаем обновление с более общей ошибкой сохранения и вот ее уже преобразуем к какому-то коду и завершаем с ним программу

2020-11-24 12:40 UTC, chrnsv commented on Sources/Run/main.swift
> +var result = 4747
А почему не
```swift
let result = try localisationHelper()
```

2020-11-24 12:40 UTC, chrnsv commented on Sources/localisation-helper/Dictionary.swift
> +            throw ValidationResult.failedToWrite
`read`?

2020-11-24 12:40 UTC, chrnsv commented on Sources/localisation-helper/TemplateOptions.swift
> +//  TestTerminalOutput.swift
Почему?)

2020-11-24 12:40 UTC, chrnsv commented on Sources/localisation-helper/localisation-helper.swift
> +    return 0
Сейчас получилась странная ситуация, если мы не закончим раньше по throw, то получим код 0, при этом в таргете `Run` мы обработаем только код, ошибка просто провалится дальше, выглядит не очень круто

2020-11-24 12:40 UTC, chrnsv commented on Tests.sh
> +  if [ "$exitCode" == 0 ]; then
Сейчас получается так, что успешный – любой тест, который завершился с кодом 0, а это не совсем верно. Код ноль говорит о том, что программа завершилась успешно, но когда мы запускаем программу с заведомо неправильными параметрами, мы ожидаем, что она завершится с кодом, отличным от нуля и это будет для нас маркером успеха, а код 0 в таком случае будет маркером неудачи при тесте.

Например, тестируем обновление, но не пишем ключ -l и его значение. Ожидаем, что программа не сможет обновить слово, потому что не был передан аргумент, отвечающий за язык и завершится с кодом 123, означающим, что не получилось распарсить аргументы. Если же она завершится с кодом 0, это будет означать, что она успешно обновила слово, что не совпадает с ожидаемым результатом

2020-11-24 12:40 UTC, chrnsv commented on Tests/localisation-helperTests/MockDictionary.swift
> +        writeParameters = ["hello": ["en": "hello"]]
Эм, но во `writeParameters` же должно было записаться то значение, с которым мы зашли в эту функцию, то есть `dictionary`?

2020-11-24 12:40 UTC, chrnsv commented on Tests/localisation-helperTests/TestArgumentParser.swift
> +                XCTAssertTrue(true, ValidationResult.parseWentWrong.errorDescription!)
А как `ValidationResult.parseWentWrong.errorDescription!` может быть `true`? И зачем проверять что `true` == `true`?)

2020-11-24 12:40 UTC, chrnsv commented on Tests/localisation-helperTests/TestDeleteOption.swift
> +        do {
А что проверяет этот тест?

Мы хотим чтобы у нас успешно удалилось слово с ключом "hello" и языком "en"? Тогда нам нужно организовать все условия для этого

1. Сделать так, чтобы dict вернул словарь, в котором есть это слово
2. Проверить, что мы запросили слова из dict
2. Проверить что в качестве удаленного слова в output попало именно то, которое мы ожидаем
3. Проверить, что в качестве сообщения с новым словарем получилось сообщение без этого слова
4. Проверить, что мы сохранили в dict новый словарь без этого слова

Давай все тесты так доработаем

2020-11-26 13:30 UTC, chrnsv approved these changes
[Вот тут](https://github.com/ksko-git/localization-helper-application-on-swift/pull/7/files#r529495152) еще писал по поводу `public`, давай все-таки поправим

2020-11-26 13:30 UTC, chrnsv commented on Sources/localisation-helper/Search.swift
> +        } catch let error as ValidationResult {
Ну не, давай уж лучше тогда как было)

Спроси меня в начале следующей пары, что я имел в виду по поводу ошибок

2020-11-26 13:30 UTC, chrnsv commented on Sources/localisation-helper/SearchProtocol.swift
> +    func defaultSearch(dictionary: [String: [String: String]])
Если `defaultSearch` не вызывается за пределами класса, то его нужно сделать приватным и убрать из протокола

2020-11-26 13:30 UTC, chrnsv commented on Sources/localisation-helper/ValidationResult.swift
> +    public var errorDescription: String {
Вот это хорошо)

2020-11-26 13:30 UTC, chrnsv commented on Sources/Run/main.swift
> +    let _ = try localisationHelper()
Можно `let _ =` опустить

2020-11-26 13:30 UTC, chrnsv commented on Tests/localisation-helperTests/MockTerminalOutput.swift
> +    var consoleOutputParameters: (word: String, Void)?
Можно не делать кортеж, если аргумент один и писать `: String?`

2020-11-26 16:38 UTC, merged